server.port=8090

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/content_management_db
spring.data.mongodb.database=content_management_db

# No JPA configuration needed (MongoDB, not SQL)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# JWT Configuration
app.jwtSecret=mySecretKeyForJWTTokenProviderApplicationShouldBeAtLeastThirtyTwoCharactersLongForHS256Algorithm
app.jwtExpirationMs=86400000
ml.service.url=http://localhost:8000

# ============================================================
# EMAIL CONFIGURATION
# ============================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=wafarz78@gmail.com
spring.mail.password=fmdxbjgjznjfmocn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000